### ISSUE TITLE
Osram LIGHTIFY ClA60 RGBW LED doesn't work properly

### ISSUE THREAD

**Issue by fabian1512** [mdaskalov/homebridge-tasmota-zbbridge#10] opened 2022-01-27 10:22 UTC
@mdaskalov: first of all: thanks a lot for the plugin. although the plugin has been around for a while, I only discovered it now.

I have integrated my previous zigbee devices (temperature sensors) into homebridge using mqttthings, but I want to move them to your plugin when the time comes.
I was once able to successfully control my rgb lamp via my CC2531. Since moving to the ZbBridge, I have no longer been able to manage the colour selection. I was therefore very pleased about your plugin.
However, I have two problems:
1. i can only switch the lamp on and off, setting the colour does not work. in homekit i cannot change the colour (the buttons are displayed slightly pale and cannot be selected).
2. after switching on the lamp via a normal light switch, the changed state (on) is not displayed in homekit. the button remains as switched off

I tried:
1. Changing between "RGB light" and "RGB (with XY...)"
2. in ZbBridge console changing "zblight 0x4c9a,3 (RGB light) and 4 (RGBW light)

both didn`t help
What else can i do?

thank you in advance 

**Plugin Config:**
        {
            "name": "ZbBridge",
            "mqttTopic": "zbbridge",
            "zbBridgeDevices": [
                {
                    "addr": "0x4c9a",
                    "type": "light3",
                    "name": "Licht_Flur"
                }
            ],
            "mqttBroker": "192.168.1.51",
            "platform": "TasmotaZbBridge"
        }

**Environment:**

* **Plugin Version**: latest
* **Homebridge Version**:  latest
* **Node.js Version**:  latest
* **NPM Version**:  latest
* **Operating System**: 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
version 10.11

**Comment by mdaskalov** [comment] 2022-01-27 15:05
Use first `ZbLight 0x4c9a, 4` to tell ZbBridge that you have RGBW bulb. And also configure it as `light4` in homebridge. If the color controls are not shown in the Home app try to set some color manually: 
```
ZbSend { "device":"0x4c9a", "send":{"HueSat":"200,100"} }
```
I think that sometimes detecting RGB lights doesn’t work properly but had got no time to debug it. I have two buggy "lidl" GU10 bulbs which have the color controls disabled (not working) each time I restart homebridge.

**Comment by fabian1512** [comment] 2022-01-27 18:33
thank you for your help. the status in homekit remains unchanged. after double-clicking (on the mac) on the button, the six preset colours flicker. then they remain pale and cannot be selected.
After restarting Homebridge, the tile reports "no response". Only after I have switched the light on and off once in homebridge under „devices“,  the light seem to be "connected" to homekit.

If you don't have any other ideas, I'll just wait and see, maybe you'll get it to work some time. At least I'm happy that I can turn the light on and off and dim it.

**Comment by mdaskalov** [comment] 2022-01-27 18:52
I will have a look at the weekend and let you know if I find something. You can also try previous versions. 
The `ZbSend` command above helps to get the color buttons working. I’ve just tested it.

**Comment by fabian1512** [comment] 2022-01-28 07:36
Thank you very much, that was a good hint.
With version v0.9.0 the colours were selectable. Only when setting the colour, the selection circle always jump back to the centre. This behaviour was OK with v0.10.0.
Afterwards I installed v0.10.1 again. The colour selection is still possible. Only dimming is no longer possible. The colours set also do not correspond exactly to the colours of the lamp.

**Comment by mdaskalov** [comment] 2022-01-28 19:07
The colors should match. 
Please check the color shown on the main menu of ZbBridge - it should be the same as in the home app.

It is fixed in 0.12.1 - it was because of the `reachable` flag which was undefined (unreachable) at the beginning preventing any status updates to be submitted. Please confirm, so I can close this.

**Comment by fabian1512** [comment] 2022-01-28 20:12
I am sorry - same behavior as before - cannot select the colors. 
Even uninstalled the plugin completely and reinstalled.
Maybe I have to set the endpoint? Do you have an advice how to find?

**Comment by mdaskalov** [comment] 2022-01-29 12:03
Please try 0.12.2 and give me feedback. I tweaked some more things and hope that this will help. There are still issues with the initialization after reboot... I will work on it if I got some free time.
If your bulb is initially unreachable try to switch it on and then off few times so it could be updated.

**Comment by fabian1512** [comment] 2022-01-29 16:16
I reinstalled, restarted, but the colors don't show up
I can imagine that this annoys you. but for me, you don't have to worry. maybe you'll find a solution at the next opportunity.
let me know if you need any data, such as log files, etc. from me.

**Comment by mdaskalov** [comment] 2022-01-29 16:55
I am just curious why it does not work. Seems that your bulb doesn’t react on status updates. 

Please try following status update requests in the ZbBridge console (replace device address if necessary):

Get HueSat:
```
ZbSend { "Device": "0x4c9a", "Cluster": 768, "Read": [0, 1] }
```
Get XY Color:
```
ZbSend { "Device": "0x4c9a", "Cluster": 768, "Read": [3, 4 ] }
```
Get CT:
```
ZbSend { "Device": "0x4c9a", "Cluster": 768, "Read": 7 }
```

The color controls should be visible after these commands, if value updates are returned from your bulb.

You can also try to enable "Homebridge Debug Mode -D" in the "Homebridge Settings" menu of the "homebridge-config-ui-x" plugin. It could be necessary to disable other plugins as the log could be very long. Then you can look for following (or similar):
```
[ZbBridge] Licht_Flur (0x4C9A) updateColor: ColorMode: 0, Dimmer: 41%, Hue: 232, Saturation: 100
```

**Comment by fabian1512** [comment] 2022-01-29 17:29
in the homebridge.log there are no responds. In Console I did
sudo tail -f /var/lib/homebridge/homebridge.log | grep ZbBridge

in ZbBridge Console I read this

18:19:03.419 CMD: ZbSend { "Device": "0x4c9a", "Cluster": 768, "Read": [3, 4 ] }
18:19:03.420 SRC: WebConsole from 192.168.1.38
18:19:03.422 CMD: Grp 0, Cmnd 'ZBSEND', Idx 1, Len 55, Data '{ "Device": "0x4c9a", "Cluster": 768, "Read": [3, 4 ] }'
18:19:03.425 ZIG: guessing endpoint 3
18:19:03.426 ZigbeeZCLSend device: 0x4C9A, group: 0x0000, endpoint:3, cluster:0x0300, cmd:0x00, send:"03000400"
18:19:03.427 ZIG: ZbEZSPSend 3400009A4C0401000301034001000079010710790003000400
18:19:03.430 MQT: stat/zbbridge/RESULT = {"ZbSend":"Done"}
18:19:03.453 MQT: tele/zbbridge/Router/SENSOR = {"Router":{"Device":"0xAAE0","Name":"Router","Power":1,"Endpoint":8,"LinkQuality":71}}
18:19:03.460 ZIG: {"ZbEZSPReceived":"3400009C"}
18:19:03.495 ZIG: {"ZbEZSPReceived":"3F00009A4C040100030103400100009C010000"}
18:19:03.507 ZIG: {"ZbEZSPReceived":"45000004010003030140000000CA58B29A4CFFFF0F187901030000216B61040000217D60"}
18:19:03.509 ZIG: {"ZbZCLReceived":{"groupid":0,"clusterid":"0x0300","srcaddr":"0x4C9A","srcendpoint":3,"dstendpoint":1,"wasbroadcast":0,"LinkQuality":24,"securityuse":0,"seqnumber":202,"fc":"0x18","frametype":0,"direction":1,"disableresp":1,"manuf":"0x0000","transact":121,"cmdid":"0x01","payload":"030000216B61040000217D60"}}
18:19:03.511 ZIG: ZbZCLRawReceived: {"0x4C9A":{"0300/0003":24939,"0300/0004":24701,"Endpoint":3,"LinkQuality":24}}
18:19:03.911 MQT: tele/zbbridge/Treppenlicht/SENSOR = {"Treppenlicht":{"Device":"0x4C9A","Name":"Treppenlicht","X":24939,"Y":24701,"RGB":"FAD4A7","RGBb":"FAD4A7","Endpoint":3,"LinkQuality":24}}
18:19:04.089 ZIG: {"ZbEZSPReceived":"4500000401060008010001000014A0C4E0AAFFFF07000D0A00002001"}

**Comment by mdaskalov** [comment] 2022-01-29 18:23
The problem is that you have set `SetOption89 1` and the topic is device specific. Please also disable `SetOption100` (`ZbNoPrefix`) to have the keyword `ZbReceived` in the message.
That’s why the SENSOR response is never received and thus no status update is possible.

The expected answer is:
```
18:19:03.911 MQT: tele/zbbridge/SENSOR =  {"ZbReceived":{"0xD749":{"Device":"0x4C9A","Name":"Treppenlicht","X":24939,"Y":24701,"RGB":"FAD4A7","RGBb":"FAD4A7","Endpoint":3,"LinkQuality":24}}
```

So please execute in the ZbBridge console:
```
SetOption89 0
SetOption100 0
```

**Comment by fabian1512** [comment] 2022-01-29 19:08
although I don't remember changing these options, I set them according to your instructions.

no answers on debug-mode in homebridge.log.

However, I always saw answers from my router (CC2531) in the zbbridge log. I switched it off and now have this in the zbbridge log:

20:07:38.444 CMD: ZbSend { "Device": "0x4c9a", "Cluster": 768, "Read": [3, 4 ] }
20:07:38.446 SRC: WebConsole from 192.168.1.38
20:07:38.447 CMD: Grp 0, Cmnd 'ZBSEND', Idx 1, Len 55, Data '{ "Device": "0x4c9a", "Cluster": 768, "Read": [3, 4 ] }'
20:07:38.450 ZIG: guessing endpoint 3
20:07:38.452 ZigbeeZCLSend device: 0x4C9A, group: 0x0000, endpoint:3, cluster:0x0300, cmd:0x00, send:"03000400"
20:07:38.453 ZIG: ZbEZSPSend 3400009A4C04010003010340010000C5010710C50003000400
20:07:38.457 MQT: stat/zbbridge/RESULT = {"ZbSend":"Done"}
20:07:38.484 ZIG: {"ZbEZSPReceived":"34000061"}
20:07:38.523 ZIG: {"ZbEZSPReceived":"3F00009A4C0401000301034001000061010000"}
20:07:38.538 ZIG: {"ZbEZSPReceived":"450000040100030301400000007D48AE9A4CFFFF0F18C501030000210088040000210075"}
20:07:38.540 ZIG: {"ZbZCLReceived":{"groupid":0,"clusterid":"0x0300","srcaddr":"0x4C9A","srcendpoint":3,"dstendpoint":1,"wasbroadcast":0,"LinkQuality":14,"securityuse":0,"seqnumber":125,"fc":"0x18","frametype":0,"direction":1,"disableresp":1,"manuf":"0x0000","transact":197,"cmdid":"0x01","payload":"030000210088040000210075"}}
20:07:38.542 ZIG: ZbZCLRawReceived: {"0x4C9A":{"0300/0003":34816,"0300/0004":29952,"Endpoint":3,"LinkQuality":14}}
20:07:38.942 MQT: tele/zbbridge/SENSOR = {"ZbReceived":{"Treppenlicht":{"Device":"0x4C9A","Name":"Treppenlicht","X":34816,"Y":29952,"RGB":"FA9E00","RGBb":"EB9500","Endpoint":3,"LinkQuality":14}}}

**Comment by mdaskalov** [comment] 2022-01-29 20:23
Now it looks fine! 
Try following to get the color controls (you have configured your bulb as `light3` (RGB Light) which controls the color with Hue and Saturation): 
```
ZbSend { "Device": "0x4c9a", "Cluster": 768, "Read": [0, 1] }
```
if this doesn’t work you can change it to "RGB (With XY Color and CT)

To control both RGB and CT you can configure  following JSON directly (support Brightness, HueSat and CT):
```
{
  "addr": "0x4c9a",
  "type": "light_B_HS_CT",
  "name": "Treppenlicht"
}
```

**Comment by fabian1512** [comment] 2022-01-31 13:37
Now it has worked.

Yesterday, after I had changed all the rules in node red because of the 
SetOption89 0
SetOption100 0
I tried to get a temperature sensor to talk. 
I noticed that my ZbReceived messages look like this:
{"ZbReceived":{" FriendlyName":{"Device":"....
But you had described the expected message above like this:
{"ZbReceived":{" shortaddress":{"Device":"....

In fact it works fine with 
SetOption83, 0
(Uses Zigbee device friendly name instead of 16 bits short addresses).
[**EDIT**]I had to turn back 
SetOption89 1
because otherwise I won't get my brightness sensor to talk via mqttthings..

However, this means that I have to adjust all the rules in node red again. 
However, "SetOption83, 1" makes everything (e.g. in node red and in the Mqtt explorer) somewhat clearer.
Is there any chance that you can adjust this in your code?

however, I can just say thank you for your time and your help.

One last question: via my CC2531 and zigbee2mqtt, I was able to get 
"remember_state": true
to save the settings in case of a power loss.
Do you have an idea how the message via the ZbBridge could look like?

**Comment by mdaskalov** [comment] 2022-02-08 10:26
I will support `SetOption89` and `SetOption100` (and probably `SetOption83`) in one of the next releases. Will try to detect the current setting - if this doesn’t work I will add extra configuration settings.
There is no similar feature as this `remember_state` in zigbee2mqtt, as far as I know. 
Normally all lightbulbs are switched on after power loss. The easiest is to use the hue bridge to reprogram the bulb (if you have one). 
There is surely a low-level command for this, which can be used with ZbBridge. Try to dump the traffic between zigbee2mqtt and your bulb to figure out what command is used for that. Let me know if you find out!

**Comment by mdaskalov** [comment] 2022-02-12 12:21
The latest release v1.1.0 works with any combination of the options mentioned above.

**Comment by fabian1512** [comment] 2022-02-14 08:19
I installed the new version at the weekend and after restarting homebridge the lamp worked perfectly.

Thank you very much for your help. I think with this solution many others can use this comfortable plugin right away.

rember_state: so far I have no idea how to get a dump from the traffic. I'll take a look at it when I get a chance and then maybe come back to your help.

**Closed as completed** 2022-02-14 08:19 UTC
Labels: question
